// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttons': string;
  'color': string;
  'color_btn': string;
  'color_picker': string;
  'delete_btn': string;
  'delete_icon': string;
  'folder_setting': string;
  'picker': string;
  'rename_btn': string;
  'rename_icon': string;
}
export const cssExports: CssExports;
export default cssExports;
