// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'color': string;
  'color_btn': string;
  'delete_btn': string;
  'delete_icon': string;
  'folder_setting': string;
  'move_btn': string;
  'move_icon': string;
  'picker': string;
}
export const cssExports: CssExports;
export default cssExports;
