// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'delete_btn': string;
  'delete_icon': string;
  'memo_setting': string;
  'move_btn': string;
  'move_icon': string;
}
export const cssExports: CssExports;
export default cssExports;
