// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'add': string;
  'add_memo_btn': string;
  'date': string;
  'memo': string;
  'memo_list_container': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
