// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'folder': string;
  'folder_list_container': string;
}
export const cssExports: CssExports;
export default cssExports;
