// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'add': string;
  'folder': string;
  'folder_container': string;
  'folder_list': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
