// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'deleteBtn': string;
  'deleteIcon': string;
  'memoMore': string;
  'moveBtn': string;
  'moveIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
