// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'tip': string;
  'tooltip_container': string;
}
export const cssExports: CssExports;
export default cssExports;
