// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'align': string;
  'bold': string;
  'center': string;
  'divider': string;
  'edit_area': string;
  'edit_container': string;
  'folder': string;
  'image': string;
  'italic': string;
  'justified': string;
  'left': string;
  'link': string;
  'logo': string;
  'right': string;
  'strike': string;
  'table': string;
  'toolbar': string;
  'underline': string;
}
export const cssExports: CssExports;
export default cssExports;
