// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'folder_body': string;
  'folder_container': string;
  'folder_header': string;
}
export const cssExports: CssExports;
export default cssExports;
