// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'add': string;
  'addMemoBtn': string;
  'date': string;
  'memo': string;
  'memoList': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
