// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'align': string;
  'bold': string;
  'divider': string;
  'edit_area': string;
  'edit_container': string;
  'folder': string;
  'italic': string;
  'logo': string;
  'removeline': string;
  'toolbar': string;
  'underline': string;
}
export const cssExports: CssExports;
export default cssExports;
