// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'color': string;
  'colorBtn': string;
  'deleteBtn': string;
  'deleteIcon': string;
  'folderMore': string;
  'moveBtn': string;
  'moveIcon': string;
  'picker': string;
}
export const cssExports: CssExports;
export default cssExports;
