// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'backBtn': string;
  'header': string;
  'homeBtn': string;
  'homeBtnDiv': string;
  'logoutBtn': string;
  'selectBtn': string;
  'selectBtnActive': string;
}
export const cssExports: CssExports;
export default cssExports;
