// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'back_btn': string;
  'header': string;
  'home_btn': string;
  'home_btn_div': string;
  'logout_btn': string;
  'save_btn': string;
  'select_btn': string;
  'select_btn_active': string;
}
export const cssExports: CssExports;
export default cssExports;
